export const ROUTES = {
  HOME: "/home",
  LANDINGPAGE: "/",
  LEGAL: "/legal",
  ABOUT: "/about",
  FEATURES: "/features",
  CONTACTS: "/contacts",
  LOGIN: "/login",
  REGISTER: "/register",
  RESET_PASSWORD: "/reset_password",
  RESEND_CODE: "/reset_password",
  FINANCIAL: "/home/goals",
  FINANCIAL_OBJECTIVE: "/home/goals/objective",
  FINANCIAL_NEW_OBJECTIVE: "/home/goals/new",
  FINANCIAL_IA: "/home/goals/ia",
  LIBRARY: "/home/library",
  ARTICLE: "/home/library/article",
  PROFILE: "/home/profile",
  CATEGORIES: "/home/categories",
  CHAT_IA: "/home/chat",
  CONTROL_PANEL: "/home/analytics",
  SUPPORT: "/home/profile/support",
  SCAN: "/home/scan",
  VERIFY_PENDING: "/verify-pending",
  VERIFY_EMAIL: "/verify-email",
} as const;
