export const ROUTES = {
  HOME: "/home",
  LANDINGPAGE: "/",
  LEGAL: "/legal",
  ABOUT: "/about",
  FEATURES: "/features",
  CONTACTS: "/contacts",
  LOGIN: "/login",
  REGISTER: "/register",
  RESET_PASSWORD: "/reset_password",
  RESEND_CODE: "/.....",
  FINANCIAL: "/home/financial",
  FINANCIAL_OBJECTIVE: "/home/financial/objective",
  FINANCIAL_NEW_OBJECTIVE: "/home/financial/new",
  FINANCIAL_IA: "/home/financial/ia",
  LIBRARY: "/home/library",
  ARTICLE: "/home/library/article",
  PROFILE: "/home/profile",
  CHAT_IA: "/home/chat",
  CONTROL_PANEL: "/home/profile/control_panel",
  SUPPORT: "/home/profile/support",
  SCAN: "/home/scan",
} as const;
