export const ROUTES = {
  HOME: '/home',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  RESET_PASSWORD: '/auth/reset_password',
  RESEND_CODE: '/auth/register',
  FINANCIAL: '/home/financial',
  FINANCIAL_OBJECTIVE: '/home/financial/objective',
  FINANCIAL_NEW_OBJECTIVE: '/home/financial/new',
  FINANCIAL_IA: '/home/financial/ia',
  LIBRARY: '/home/library',
  ARTICLE: '/home/library/article',
  PROFILE: '/home/profile',
  CHAT_IA: '/home/chat',
  CONTROL_PANEL: '/home/profile/control_panel',
  SCAN: '/home/scan',
} as const;