import {
  Wallet,
  TrendingUp,
  ArrowRight,
  CheckCircle2,
  BarChart3,
  PieChart,
  Tag,
  Home,
  FileText,
  CreditCard,
  Target,
  MessageSquare,
} from "lucide-react";
import type { Tutorial } from "@/types/dtos/tutorial.dto";

export const tutorials: Tutorial[] = [
  {
    id: "tutorial-first-revenue",
    name: "Primeira Receita",
    description: "Aprenda a registar a sua primeira receita",
    showOnce: true,
    steps: [
      {
        id: "welcome",
        title: "Bem-vindo ao Wundu!",
        text: "Vamos mostrar-lhe como registar receitas. Este guia informativo vai explicar cada funcionalidade.",
        targetSelector: "[data-tutorial='upload-section']",
        placement: "right",
        icon: Wallet,
      },
      {
        id: "add-transaction",
        title: "Adicionar Transação",
        text: "Clique neste card para começar. Pode enviar um comprovativo (PDF, JPG) ou fazer um lançamento manual.",
        targetSelector: "[data-tutorial='upload-section']",
        placement: "bottom",
        icon: ArrowRight,
      },
      {
        id: "stats-overview",
        title: "Visão Geral",
        text: "Aqui vê o resumo das suas finanças: total de transações, receitas e despesas do mês.",
        targetSelector: "[data-tutorial='stats-revenue']",
        placement: "bottom",
        icon: BarChart3,
      },
      {
        id: "transactions-list",
        title: "Lista de Transações",
        text: "As suas transações aparecem aqui, organizadas por data. Receitas a verde, despesas a vermelho.",
        targetSelector: "[data-tutorial='movement-section']",
        placement: "top",
        icon: CreditCard,
      },
    ],
  },
  {
    id: "tutorial-revenue-stats",
    name: "Estatísticas de Receitas",
    description: "Veja como as suas receitas são apresentadas",
    showOnce: true,
    steps: [
      {
        id: "stats-revenue-card",
        title: "Card de Receitas",
        text: "Este card mostra o total de receitas do mês. É atualizado automaticamente quando adiciona novas receitas.",
        targetSelector: "[data-tutorial='stats-revenue']",
        placement: "bottom",
        icon: TrendingUp,
      },
      {
        id: "transactions-list",
        title: "Lista de Transações",
        text: "As suas receitas aparecem nesta lista, organizadas por data. Clique numa transação para ver detalhes.",
        targetSelector: "[data-tutorial='movement-section']",
        placement: "top",
        icon: BarChart3,
      },
    ],
  },
  {
    id: "tutorial-categories",
    name: "Categorias de Receitas",
    description: "Gerencie as categorias das suas receitas",
    showOnce: true,
    steps: [
      {
        id: "categories-nav",
        title: "Navegação",
        text: "Acesse 'Categorias' no menu lateral para ver e gerenciar todas as categorias de receitas e despesas.",
        targetSelector: "[data-tutorial='nav-categories']",
        placement: "right",
        icon: Tag,
      },
      {
        id: "categories-tabs",
        title: "Abas de Categorias",
        text: "Use as abas para alternar entre Resumo, Sistema e Personalizadas. Cada aba mostra informações diferentes.",
        targetSelector: "[data-tutorial='categories-tabs']",
        placement: "bottom",
        icon: BarChart3,
      },
      {
        id: "categories-toggle-revenue",
        title: "Filtro Receitas",
        text: "Clique em 'Receitas' para ver apenas as categorias de receitas e o total recebido este mês.",
        targetSelector: "[data-tutorial='categories-toggle-receita']",
        placement: "bottom",
        icon: TrendingUp,
      },
    ],
  },
  {
    id: "tutorial-analytics",
    name: "Análises de Receitas",
    description: "Visualize gráficos e análises das suas receitas",
    showOnce: true,
    steps: [
      {
        id: "analytics-nav",
        title: "Análises",
        text: "Acesse 'Análises' no menu lateral para ver gráficos detalhados das suas receitas e despesas.",
        targetSelector: "[data-tutorial='nav-analytics']",
        placement: "right",
        icon: BarChart3,
      },
      {
        id: "analytics-chart-toggle",
        title: "Tipo de Gráfico",
        text: "Escolha entre gráfico de linhas, barras ou pizza para visualizar os seus dados de diferentes formas.",
        targetSelector: "[data-tutorial='analytics-chart-type']",
        placement: "bottom",
        icon: PieChart,
      },
      {
        id: "analytics-revenue-toggle",
        title: "Filtro Receitas",
        text: "Ative o toggle 'Receitas' para incluir as receitas no gráfico. Pode ver receitas e despesas separadamente ou juntas.",
        targetSelector: "[data-tutorial='analytics-revenue-toggle']",
        placement: "bottom",
        icon: TrendingUp,
      },
      {
        id: "analytics-time-range",
        title: "Período",
        text: "Selecione o período: 1 dia, 1 semana, 1 mês, 6 meses ou 1 ano para analisar tendências.",
        targetSelector: "[data-tutorial='analytics-time-range']",
        placement: "bottom",
        icon: BarChart3,
      },
      {
        id: "analytics-summary",
        title: "Resumo",
        text: "Veja o card de resumo com o total de receitas, despesas e saldo do período selecionado.",
        targetSelector: "[data-tutorial='analytics-summary']",
        placement: "top",
        icon: Wallet,
      },
    ],
  },
  {
    id: "tutorial-navigation",
    name: "Navegação",
    description: "Conheça o menu de navegação",
    showOnce: true,
    steps: [
      {
        id: "nav-home",
        title: "Início",
        text: "O painel inicial mostra um resumo das suas finanças com transações recentes e estatísticas.",
        targetSelector: "[data-tutorial='nav-home']",
        placement: "right",
        icon: Home,
      },
      {
        id: "nav-goals",
        title: "Objectivos",
        text: "Defina metas financeiras e acompanhe o progresso. Pode criar objectivos de curto e longo prazo.",
        targetSelector: "[data-tutorial='nav-goals']",
        placement: "right",
        icon: Target,
      },
      {
        id: "nav-analytics",
        title: "Análises",
        text: "Visualize gráficos e relatórios detalhados das suas receitas e despesas por período.",
        targetSelector: "[data-tutorial='nav-analytics']",
        placement: "right",
        icon: BarChart3,
      },
      {
        id: "nav-categories",
        title: "Categorias",
        text: "Organize suas transações por categorias. Crie categorias personalizadas e defina limites mensais.",
        targetSelector: "[data-tutorial='nav-categories']",
        placement: "right",
        icon: Tag,
      },
      {
        id: "nav-chat",
        title: "Wundu AI",
        text: "Use a inteligência artificial para tirar dúvidas e obter insights sobre suas finanças.",
        targetSelector: "[data-tutorial='nav-chat']",
        placement: "right",
        icon: MessageSquare,
      },
    ],
  },
];
